services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    depends_on:
      - migrate
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: your_mysql_password
      DATABASE_NAME: eurotennis
    volumes:
      - .:/app
      - /app/node_modules # Important to exclude node_modules from host.
    command: npm run dev
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: eurotennis
    volumes:
      - mysql-data:/var/lib/mysql
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: your_mysql_password
      DATABASE_NAME: eurotennis

volumes:
  mysql-data: