services:


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: eurotennis
      MYSQL_ROOT_HOST: '%'
      # This line ensures the root user uses mysql_native_password
      MYSQL_ROOT_PASSWORD_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_mysql_password
    depends_on:
      - db

volumes:
  mysql-data: